"""phase2_photos_tags

Revision ID: 92cf6b3a8ccd
Revises: 5e8d4b6620f8
Create Date: 2026-06-21 11:43:57.092070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cf6b3a8ccd'
down_revision: Union[str, Sequence[str], None] = '5e8d4b6620f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Constraint may already exist from initial migration; skip if present.
    from sqlalchemy import text
    bind = op.get_bind()
    result = bind.execute(
        text("SELECT 1 FROM pg_constraint WHERE conname = 'uq_profile_tag'")
    ).fetchone()
    if not result:
        op.create_unique_constraint('uq_profile_tag', 'profile_tags', ['profile_id', 'tag_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_profile_tag', 'profile_tags', type_='unique')
    # ### end Alembic commands ###
